### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by vivac0209**
Hi 老師, 
我是詹沛鋆,discord: viva

Please check test url. Thank you.

http://34.196.200.104:3000/api/attraction/6
http://34.196.200.104:3000/api/attractions?page=1
http://34.196.200.104:3000/api/attractions?page=0&keyword=溫泉

### CODE REVIEW

**Comment by cwpeng** [comment]
1. Add rule to your `main` branch: at least 1 review approval before merging.
2. "nextPage" in http://34.196.200.104:3000/api/attractions?page=4 should be null, not [null]
3. "nextPage" in http://34.196.200.104:3000/api/attractions?page=0&keyword=%E9%A4%A8 should be 1, not null. Because there is page 1 in this searching results.
4. "images" of attraction data should be an array containing image URLs separately for a single attraction.

Fix issues and leave comment for me to review again.

**Comment by vivac0209** [comment]
Hi 老師,
The bugs are fixed. please check. thank you!

http://34.196.200.104:3000/api/attraction/5
http://34.196.200.104:3000/api/attractions?page=4
http://34.196.200.104:3000/api/attractions?page=0&keyword=館

**Comment by cwpeng** [comment]
Never get all data just for count of rows. I means SQL below should use count(*) to get count of rows, and you should update any related code necessary.
```
sqlCount =f"SELECT * FROM `viewList` WHERE name LIKE '%{keyword}%' or '%{keyword}' or '{keyword}%';"
```

**Comment by vivac0209** [comment]
Hi 老師,
我是詹沛鋆,discord: viva

Fixed the bug. please check,again. thank you!
(sqlCount =f"SELECT * FROM `viewList` WHERE name LIKE '%{keyword}%' or '%{keyword}' or '{keyword}%';")
http://35.168.235.19:3000/api/attraction/5
http://35.168.235.19:3000/api/attractions?page=4
http://35.168.235.19:3000/api/attractions?page=0&keyword=%E9%A4%A8

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
